In [22]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/shuofxz/titanic-machine-learning-from-disaster/train.csv
/kaggle/input/datasets/shuofxz/titanic-machine-learning-from-disaster/test.csv

In [23]:
titanic=pd.read_csv('/kaggle/input/datasets/shuofxz/titanic-machine-learning-from-disaster/train.csv')
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [25]:
titanic.isnull().head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False

In [26]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [27]:
titanic['Age']=titanic['Age'].fillna(titanic['Age'].median())

titanic=titanic.drop(columns=['Cabin'])

titanic['Embarked']=titanic['Embarked'].fillna(titanic['Embarked'].mode()[0])

In [28]:
titanic.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [29]:
print(titanic['Sex'].unique())

print(titanic['Embarked'].unique())

['male' 'female']
['S' 'C' 'Q']

In [30]:
print(titanic['Age'].describe())
print(titanic['Fare'].describe())

count    891.000000
mean      29.361582
std       13.019697
min        0.420000
25%       22.000000
50%       28.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64
count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [31]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
titanic['Fare_normalized'] = scaler.fit_transform(titanic[['Fare']])

scaler2 = StandardScaler()
titanic['Age_standardized'] = scaler2.fit_transform(titanic[['Age']])

titanic[['Age', 'Age_standardized', 'Fare', 'Fare_normalized']].head()

    Age  Age_standardized     Fare  Fare_normalized
0  22.0         -0.565736   7.2500         0.014151
1  38.0          0.663861  71.2833         0.139136
2  26.0         -0.258337   7.9250         0.015469
3  35.0          0.433312  53.1000         0.103644
4  35.0          0.433312   8.0500         0.015713

In [32]:
print(titanic['Sex'].value_counts())

print(titanic['Embarked'].value_counts())

Sex
male      577
female    314
Name: count, dtype: int64
Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

In [33]:
titanic['Sex'] = titanic['Sex'].map({'male': 1, 'female': 0})

# Embarked - One Hot Encoding
titanic = pd.get_dummies(titanic, columns=['Embarked'])

# Result చూద్దాం
titanic[['Sex', 'Embarked_S', 'Embarked_C', 'Embarked_Q']].head()

   Sex  Embarked_S  Embarked_C  Embarked_Q
0    1        True       False       False
1    0       False        True       False
2    0        True       False       False
3    0        True       False       False
4    1        True       False       False

In [34]:
titanic['Embarked_S'] = titanic['Embarked_S'].astype(int)
titanic['Embarked_C'] = titanic['Embarked_C'].astype(int)
titanic['Embarked_Q'] = titanic['Embarked_Q'].astype(int)

titanic[['Sex', 'Embarked_S', 'Embarked_C', 'Embarked_Q']].head()

   Sex  Embarked_S  Embarked_C  Embarked_Q
0    1           1           0           0
1    0           0           1           0
2    0           1           0           0
3    0           1           0           0
4    1           1           0           0

In [35]:
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Fare_normalized,Age_standardized,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,0.014151,-0.565736,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0.139136,0.663861,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,0.015469,-0.258337,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,0.103644,0.433312,0,0,1
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,0.015713,0.433312,0,0,1

In [36]:
titanic = titanic.drop(columns=['Age', 'Fare'])


print(titanic.shape)
titanic.head()

(891, 13)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare_normalized,Age_standardized,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",1,1,0,A/5 21171,0.014151,-0.565736,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,1,0,PC 17599,0.139136,0.663861,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",0,0,0,STON/O2. 3101282,0.015469,-0.258337,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,1,0,113803,0.103644,0.433312,0,0,1
4,5,0,3,"Allen, Mr. William Henry",1,0,0,373450,0.015713,0.433312,0,0,1

In [37]:
titanic.to_csv('titanic_cleaned.csv', index=False)

print("File saved successfully!")

File saved successfully!